# Generated by Django 2.2 on 2019-09-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('publication_date', models.DateField()),
                ('tag', models.CharField(max_length=100)),
                ('phase', models.CharField(choices=[('I', 'Ideazione'), ('S', 'Sviluppo'), ('L', 'Launched')], max_length=1)),
            ],
        ),
    ]
