# Generated by Django 3.1.1 on 2020-09-23 17:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20200923_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), size=3),
        ),
    ]
