# Generated by Django 3.1.1 on 2020-10-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20200924_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tag',
            new_name='tags',
        ),
        migrations.AddField(
            model_name='post',
            name='detailed_description',
            field=models.CharField(default='No description', max_length=800),
            preserve_default=False,
        ),
    ]
